opendog:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Femur Joint Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: femur_joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Tibia Joint Position Controllers --------------------------------

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint_leg1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint_leg2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint_leg3
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_joint_leg4
    pid: {p: 100.0, i: 0.01, d: 10.0}